root        : INFO     Namespace(cuda=True, dataset_dir='../../dataset/', filename='main_pytorch', iteration_max=40000, mode='train', subdir='models_dev', validate=True, workspace='../../experiment_workspace/Conformer-00/')
root        : INFO     The data contains: 700 training and 300 validation data.
Traceback (most recent call last):
  File "main_pytorch.py", line 342, in <module>
    train(args)
  File "main_pytorch.py", line 172, in train
    cuda=cuda)
  File "main_pytorch.py", line 48, in evaluate
    cuda=cuda)
  File "main_pytorch.py", line 99, in forward
    batch_output = model(batch_x,batch_ch,batch_3)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/Conformer-0/main/models_pytorch.py", line 309, in forward
    x1 = self.spectrogram_extractor(input1)   # (batch_size, 1, time_steps, freq_bins)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torchlibrosa/stft.py", line 658, in forward
    (real, imag) = self.stft.forward(input)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torchlibrosa/stft.py", line 237, in forward
    real = self.conv_real(x)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 260, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
root        : INFO     Namespace(cuda=True, dataset_dir='../../dataset/', filename='main_pytorch', iteration_max=40000, mode='inference_validation_data', subdir='models_dev', validate=True, workspace='../../experiment_workspace/Conformer-00/')
param number:
19305794
Traceback (most recent call last):
  File "main_pytorch.py", line 345, in <module>
    inference_validation_data(args)
  File "main_pytorch.py", line 256, in inference_validation_data
    checkpoint = torch.load(model_path)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 843, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 832, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/_utils.py", line 80, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 484, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 10.92 GiB total capacity; 267.88 MiB already allocated; 4.44 MiB free; 280.00 MiB reserved in total by PyTorch)
