root        : INFO     Namespace(cuda=True, dataset_dir='../../dataset/', filename='main_pytorch', iteration_max=12000, mode='train', subdir='models_dev', validate=True, workspace='../../experiment_workspace/baseline_cnn/')
root        : INFO     The data contains: 700 training and 300 validation data.
Traceback (most recent call last):
  File "main_pytorch.py", line 342, in <module>
    train(args)
  File "main_pytorch.py", line 172, in train
    cuda=cuda)
  File "main_pytorch.py", line 48, in evaluate
    cuda=cuda)
  File "main_pytorch.py", line 99, in forward
    batch_output = model(batch_x,batch_ch,batch_3)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/MT-3/main/models_pytorch.py", line 293, in forward
    x3 = self.cnn_encoder_3(x3)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/MT-3/main/models_pytorch.py", line 352, in forward
    x = self.conv1(x, pool_size=(2, 2), pool_type='avg')
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/MT-3/main/models_pytorch.py", line 80, in forward
    x = F.relu_(self.bn2(self.conv2(x)))
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 140, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py", line 2147, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 80.00 MiB (GPU 0; 10.92 GiB total capacity; 3.62 GiB already allocated; 29.44 MiB free; 3.67 GiB reserved in total by PyTorch)
root        : INFO     Namespace(cuda=True, dataset_dir='../../dataset/', filename='main_pytorch', iteration_max=12000, mode='inference_validation_data', subdir='models_dev', validate=True, workspace='../../experiment_workspace/baseline_cnn/')
root        : INFO     The data contains: 700 training and 300 validation data.
param number:
15117378
Traceback (most recent call last):
  File "main_pytorch.py", line 345, in <module>
    inference_validation_data(args)
  File "main_pytorch.py", line 275, in inference_validation_data
    cuda=cuda)
  File "main_pytorch.py", line 99, in forward
    batch_output = model(batch_x,batch_ch,batch_3)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/MT-3/main/models_pytorch.py", line 293, in forward
    x3 = self.cnn_encoder_3(x3)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/MT-3/main/models_pytorch.py", line 352, in forward
    x = self.conv1(x, pool_size=(2, 2), pool_type='avg')
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dstore/home/tzhou/MT-3/main/models_pytorch.py", line 78, in forward
    x = F.relu_(self.bn1(self.conv1(x)))
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/tzhou/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 80.00 MiB (GPU 0; 10.92 GiB total capacity; 3.57 GiB already allocated; 47.44 MiB free; 3.65 GiB reserved in total by PyTorch)
